---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my-dummy-secret
spec:
  encryptedData:
    password: AgDMu3WUYpymlh7ZURGALh7/fSIYB/J25VJw0uC5TenDZCPbihKRGKAZrlbQASC89lNtq6BsBg0FKDRPRithZWxE8L5enWWGGf7F9CXRV66CUexBsXeVNlVVBuFqxecdQqyRY0QBCAae2WFW9IPCuq+Tt+wekXw0srPKrYFvbLVlAu/KmEQ5UKN4GJWuleb5e9u6eO0s4AE9UibgcevavTwhQmaIULj5YyaUY+9WaWuovg9QVLiuyh2ZOKM067U2Asy/EMQwinUXYcqDCtnWDzjtF5lrnUR3UJrmYsxWcTRHknpNdwlHUxHgylk0r/lO4CXsLmeKm6tQy9HkeR2e2N3WpGU5c4I0NeEHSEgGUz0wRQ1gjoD3yJp0TLNYKK3o0WZ9GT9CXh2Yv2uwZavRryWnRPsdVdgzVWwmmRU/vbZPvaWsMhrHhY8YmfviauZHPK4i3wW3YsY9nu9YiuD9o/c1lD7QkLHNP2UHU27ByMH4LZ9b/PI0fZhfWg5hdWXZCaKCSK8HlBfoeIKo60EA9Z6OJDMvwe/qVN/3Sl6kyJ0v77a7b3xwhE7K330TmzezK7lxQSYacipO+Vvb/5MTWeqjA3pt1qbNgWgVhCnNVYK5mkJ5hohHhthKFcpvEsuQ5e5Z/wiTSt7iMfxeHBJjf4vGQBmaAUpsdl3M38WLH9SWFzzZENJSreIJgcq45IVIxf36Jis84Hpp2lfD82s=
    username: AgAGgFp/HSHdE3fPh8U1lQ7HKqQmVOavILAbDha9IuXUG5hh3sR1IWhG2Wn5B2E44kzkr9T/V88ffgxIsA67x7vi/t3n9Zorh5+t1dg8SaSIJF86oM6k1aXCEe8krMW45hqOv9ViwmoA4z742FOQ7stLyhz9ZaC1FQnrl9PotpZvTLiySm05/sI8j4KBe6tqUBHA8PPaYAa4RRCyslw6jAHxNYUbJmyr8VeCKfjdMnNfZ0ZyOGLADXnhm4VxZjFoGwSlHyk3sMwi+zYzPep2z3KUjCaQqCiX5kjedS74gemq4LQubup48Q349LcLYdYvY+k/UrL5fw7XQgVPNjX3+8QNc1wynzXNbKtGYdO1ntGLy41vy2/lM1jmfGFnWj4ae7CTp+FoDKJOo26YZGaWO0wzpqa8jVeh3Ynde3DpSLJpIUJAztkqMIR8SS5FMtw+5Q8VQTcf5GyZPI7gldDI2pw5uEMneB3f/fa6D6c7AZyKgrBCpgbMHBkJ8kIO6aorGJ+tFi2D6bzJtf1qPNr1AGF9EMqvoPXS24NOK5vfzl2nwwWSbFGKifvQUZAntSwEhMdmcxJEqIoehQWB0GTNjbQx2XcRDqvtCoZpukUg6rjE+A1SQMxdVhA0cWFC/24iRyn0mAbXu8r0vcbM1lPz0W0oq5Ly6TIkxFzzl4PtqOnPxRy8I2zGA/vkr0D+oVDFLyjc0iPd6Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my-dummy-secret
