apiVersion: v1
kind: Service
metadata:
  name: solar-system-svc
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    