apiVersion: v1
kind: Service
metadata:
 
  name: webapp-svc
  labels:
    app: webapp
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    